// Lokalna zbirka predlogov; količine veljajo za eno osebo.
const mealRecipes = [
  { id:'ovsena', kind:'breakfast', title:'Ovsena kaša z banano in orehi', minutes:10, ingredients:['60 g ovsenih kosmičev','200 ml mleka ali rastlinskega napitka','1 banana','15 g orehov','ščepec cimeta'], steps:['Kosmiče in mleko segrevaj 5–7 minut ter mešaj.','Banano nareži, orehe nasekljaj.','Kašo postrezi z banano, orehi in cimetom.'] },
  { id:'omleta', kind:'breakfast', title:'Omleta s špinačo in toastom', minutes:15, ingredients:['2 jajci','1 pest mlade špinače','1 žlička olja','2 rezini polnozrnatega kruha','1 paradižnik'], steps:['Jajci razžvrkljaj in začini.','Na olju na hitro oveni špinačo, prilij jajci in peci do čvrstega.','Postrezi s popečenim kruhom in paradižnikom.'] },
  { id:'jogurt', kind:'breakfast', title:'Jogurtova skleda s sadjem', minutes:5, ingredients:['200 g grškega jogurta','40 g ovsenih kosmičev','100 g jagodičevja','1 žlička medu'], steps:['Jogurt daj v skledo in dodaj kosmiče.','Dodaj oprano sadje in po želji pokapaj z medom.'] },
  { id:'piscanec_riz', kind:'lunch', title:'Piščanec z rižem in zelenjavo', minutes:30, ingredients:['150 g piščančjih prsi','75 g suhega riža','200 g mešane zelenjave','1 žlička olja','sol, poper in paprika'], steps:['Riž skuhaj po navodilih na embalaži.','Piščanca nareži, začini in na olju dobro prepeci do sredice.','Dodaj zelenjavo, praži 7–10 minut in postrezi z rižem.'] },
  { id:'rizota', kind:'lunch', title:'Zelenjavna rižota s parmezanom', minutes:35, ingredients:['80 g riža za rižoto','200 g bučk in korenja','¼ čebule','350 ml vroče zelenjavne jušne osnove','15 g parmezana','1 žlička olja'], steps:['Na olju popraži čebulo in narezano zelenjavo.','Dodaj riž; jušno osnovo prilivaj postopoma in mešaj približno 20 minut.','Odstavi in vmešaj parmezan.'] },
  { id:'testenine_tuna', kind:'lunch', title:'Testenine s tuno in paradižnikom', minutes:20, ingredients:['80 g suhih testenin','80 g odcejene tune','150 g pasiranega paradižnika','1 strok česna','1 žlička olja'], steps:['Testenine skuhaj po navodilih.','Na olju na kratko segrej česen, dodaj paradižnik in kuhaj 8 minut.','V omako vmešaj odcejeno tuno in testenine.'] },
  { id:'leca', kind:'lunch', title:'Lečina enolončnica', minutes:30, ingredients:['100 g kuhane leče','1 korenček','½ čebule','200 g sesekljanega paradižnika','200 ml vode ali jušne osnove','1 žlička olja'], steps:['Na olju zmehčaj čebulo in korenček.','Dodaj paradižnik, lečo in tekočino; kuhaj 15–20 minut.','Po okusu začini in postrezi.'] },
  { id:'losos', kind:'lunch', title:'Losos s kuskusom in brokolijem', minutes:25, ingredients:['150 g fileja lososa','75 g suhega kuskusa','180 g brokolija','1 žlička olja','limonin sok'], steps:['Lososa začini in peci v ponvi približno 4–5 minut na vsaki strani, do pečene sredice.','Kuskus prelij z vročo vodo po navodilih in pokrij.','Brokoli skuhaj na pari ter vse postrezi z limoninim sokom.'] },
  { id:'piscanec_salata', kind:'dinner', title:'Piščančja solata s kruhom', minutes:20, ingredients:['130 g piščančjih prsi','120 g zelene solate','1 paradižnik','½ kumare','2 rezini polnozrnatega kruha','1 žlička olja'], steps:['Piščanca začini in v ponvi dobro prepeci do sredice.','Zelenjavo operi in nareži.','Dodaj narezanega piščanca, olje in kruh.'] },
  { id:'tortilja', kind:'dinner', title:'Tortilja s fižolom in zelenjavo', minutes:15, ingredients:['1 velika tortilja','120 g odcejenega kuhanega fižola','½ paprike','1 paradižnik','2 žlici jogurta'], steps:['Fižol in narezano papriko segrej v ponvi.','Tortiljo pogrej in obloži s fižolom, papriko in paradižnikom.','Dodaj jogurt in zvij.'] },
  { id:'tuna_salata', kind:'dinner', title:'Solata s tuno in jajcem', minutes:15, ingredients:['80 g odcejene tune','1 jajce','120 g mešane solate','1 paradižnik','1 žlička olja'], steps:['Jajce trdo skuhaj približno 10 minut in olupi.','Solato operi in nareži paradižnik.','Dodaj tuno, narezano jajce in olje.'] },
  { id:'skuta_krompir', kind:'dinner', title:'Pečen krompir s skuto', minutes:35, ingredients:['250 g krompirja','120 g skute','2 žlici jogurta','1 žlička olja','drobnjak'], steps:['Krompir nareži na krhlje, dodaj olje in peci pri 200 °C približno 25–30 minut do mehkega.','Skuto zmešaj z jogurtom in drobnjakom.','Postrezi skupaj.'] },
  { id:'banana_orehi', kind:'snack', title:'Banana in orehi', minutes:2, ingredients:['1 banana','20 g orehov'], steps:['Banano olupi in postrezi z orehi.'] },
  { id:'jabolko_sir', kind:'snack', title:'Jabolko in sir', minutes:3, ingredients:['1 jabolko','40 g sira'], steps:['Jabolko operi in nareži, sir postrezi zraven.'] },
  { id:'humus', kind:'snack', title:'Korenček s humusom', minutes:5, ingredients:['1 večji korenček','60 g humusa'], steps:['Korenček operi, po potrebi olupi in nareži na palčke.','Postrezi s humusom.'] },
  { id:'skuta_sadje', kind:'snack', title:'Skuta s sadjem', minutes:5, ingredients:['150 g skute','100 g sezonskega sadja','ščepec cimeta'], steps:['Sadje operi in nareži.','Vmešaj ga v skuto in potresi s cimetom.'] }
];
